name: kaala_mandi
description: "Flutter Project For Kaala Mandi , an Olx Clone"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  get_storage: ^2.1.1
  get: ^4.6.6
  flutter_local_notifications: ^17.2.3
  toastification: ^2.3.0
  flutter_screenutil: ^5.9.3
  image_gallery_saver: ^2.0.3
  loading_animation_widget: ^1.3.0
  change_app_package_name: ^1.4.0
  google_fonts: ^6.2.1
  action_slider: ^0.7.0
  image_picker: ^1.1.2
  fluttertoast: ^8.2.8
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
assets:
  - assets/images/
  - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
